# Generated by Django 5.0.2 on 2024-03-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toyota_Legacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50, unique=True)),
                ('primer_apellido', models.CharField(max_length=50, unique=True)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
